source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'MakemojiSDK-KeyboardExtension_Example' do
  pod 'MakemojiSDK-KeyboardExtension', :path => '../.'
end

target 'Emoji Keyboard' do
  pod 'MakemojiSDK-KeyboardExtension', :path => '../.'
end

target 'MakemojiSDK-KeyboardExtension_Tests' do
  pod 'MakemojiSDK-KeyboardExtension', :path => '../.'
end